# Data Preprocessing

## Import Libraries

In [3]:
import pandas as pd          # for loading and working with data
import numpy as np           # for numerical operations
import matplotlib.pyplot as plt  # for plotting graphs
import seaborn as sns        # for prettier graphs
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

print("All libraries imported successfully!")

All libraries imported successfully!

## Load the Dataset

In [8]:
df = pd.read_csv(r"C:\Users\MINHAJ\Downloads\Data Set For Task-20260408T161732Z-3-001\Data Set For Task\1) iris.csv")
# Let's see what the data looks like
print("Shape of dataset:", df.shape)   # rows x columns
print("\nFirst 5 rows:")
df.head()

Shape of dataset: (150, 5)

First 5 rows:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
# Check basic info — column names, data types
print("=== Dataset Info ===")
df.info()

print("\n=== Basic Statistics ===")
df.describe()

=== Dataset Info ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

=== Basic Statistics ===

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [11]:
# Check for missing values
print("Missing Values in Each Column ")
print(df.isnull().sum())

Missing Values in Each Column
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [12]:
# Since iris has no missing values, let's just confirm:
print("Missing values after handling:")
print(df.isnull().sum())
print("\nAll good! ✅")

Missing values after handling:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

All good! ✅

## Encoding Categorical Variables

In [13]:
# Check unique values in the species column
print("Unique species:", df['species'].unique())
print("Data type of species column:", df['species'].dtype)

Unique species: ['setosa' 'versicolor' 'virginica']
Data type of species column: object

In [14]:
# Label Encoding — converts text to numbers
# setosa → 0, versicolor → 1, virginica → 2

le = LabelEncoder()
df['species_encoded'] = le.fit_transform(df['species'])

# Let's see the result
print("Before and After Encoding:")
print(df[['species', 'species_encoded']].head(10))

Before and After Encoding:
  species  species_encoded
0  setosa                0
1  setosa                0
2  setosa                0
3  setosa                0
4  setosa                0
5  setosa                0
6  setosa                0
7  setosa                0
8  setosa                0
9  setosa                0

In [15]:
# X = input features (what the model learns FROM)
# y = target/label (what the model is trying to PREDICT)

X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species_encoded']

print("Features (X) shape:", X.shape)
print("Target (y) shape:", y.shape)
print("\nFirst 5 rows of X:")
print(X.head())

Features (X) shape: (150, 4)
Target (y) shape: (150,)

First 5 rows of X:
   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [16]:
# StandardScaler makes all features have:
# mean = 0 and standard deviation = 1

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Let's see the difference
print("Before scaling (first 3 rows):")
print(X.head(3).values)

print("\nAfter scaling (first 3 rows):")
print(X_scaled[:3])

Before scaling (first 3 rows):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]

After scaling (first 3 rows):
[[-0.90068117  1.03205722 -1.3412724  -1.31297673]
 [-1.14301691 -0.1249576  -1.3412724  -1.31297673]
 [-1.38535265  0.33784833 -1.39813811 -1.31297673]]

In [17]:
# 80% data → model learns from this (training)
# 20% data → we test how well the model learned (testing)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, 
    test_size=0.2,      # 20% for testing
    random_state=42     # ensures same split every time you run
)

print("Training set size:", X_train.shape)
print("Testing set size:", X_test.shape)
print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))

Training set size: (120, 4)
Testing set size: (30, 4)

Training samples: 120
Testing samples: 30

In [18]:
print("=" * 40)
print("   DATA PREPROCESSING COMPLETE! ✅")
print("=" * 40)
print(f"Total samples: {len(df)}")
print(f"Features used: {list(X.columns)}")
print(f"Target classes: {list(le.classes_)}")
print(f"Training samples: {len(X_train)}")
print(f"Testing samples: {len(X_test)}")
print(f"Missing values: {df.isnull().sum().sum()}")
print("=" * 40)

========================================
   DATA PREPROCESSING COMPLETE! ✅
========================================
Total samples: 150
Features used: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
Target classes: ['setosa', 'versicolor', 'virginica']
Training samples: 120
Testing samples: 30
Missing values: 0
========================================